from typing import Any, Callable

STENCIL_BITS: int

class Window:
    pass

def get_cursor_pos(window: Window) -> tuple[float, float]: ...
def set_window_size_callback(window: Window, cb: Callable[[Window, int, int], None]) -> None: ...
def set_mouse_button_callback(window: Window, cb: Callable[[Window, int, int, int], None]) -> None: ...
def create_window(width: int, height: int, title: str, monitor: Any = None, share: Any = None) -> Window: ...
def make_context_current(window: Window) -> None: ...
def terminate() -> None: ...
def init() -> int: ...
def window_hint(hint: int, value: int) -> None: ...
def get_framebuffer_size(window: Window) -> tuple[int, int]: ...
def swap_buffers(window: Window) -> None: ...
def window_should_close(window: Window) -> bool: ...
def wait_events() -> None: ...
def post_empty_event() -> None: ...