from typing import overload


class Rect:
    def __init__(self, left: float, top: float, right: float, bottom: float) -> None:
        ...

class RRect:
    def __init__(self) -> None:
        ...

    def setRectRadii(self, rect: Rect, radiis: list[tuple[float, float]]) -> None: ...

class Paint:
    def __init__(self, *, Color: Color | None = None, AntiAlias: bool | None = None) -> None:
        ...

class Color:
    @overload
    def __init__(self, r: int, g: int, b: int) -> None: ...
    @overload
    def __init__(self, r: int, g: int, b: int, a: int) -> None: ...

class Font:
    def setSize(self, size: float) -> None: ...
    def getSize(self) -> float: ...
    def measureText(self, text: str) -> float: ...